language: node_js
node_js:
  - "7.4"

before_script:
  - npm run build

before_deploy:
  - npm install -g firebase-tools

deploy:
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}