language: node_js
node_js:
  - "7.4"

before_script:
  - npm run build
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}

notifications:
  slack: plsoftware:dkUJo3UrRbRpr2RREmWZgdwz